name: presentation_timer
description: "A Material 3 Expressive Presentation Timer."
publish_to: 'none'
# ↓バージョン文字列(バージョン+ビルド番号)
version: 5.0.0+500

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # 追加パッケージ
  flutter_soloud: ^3.4.5
  google_fonts: ^6.3.3
  provider: ^6.1.1
  package_info_plus: ^9.0.0
  dynamic_color: ^1.8.1
  shared_preferences: ^2.5.3
  # material_color_utilities: ^0.13.0  # 現状では Flutter に紐づけられているため，指定不可
  # lucide_icons は削除（標準Material Iconsを使用）

# material_color_utilities: # 現状では Flutter に紐づけられているため，オーバーライド必要
dependency_overrides:
  material_color_utilities: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 音声ファイルを配置する設定
  assets:
    - assets/sounds/

  fonts:
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/GoogleSansFlex.ttf